### ISSUE TITLE
Trace function in a dynamic library

### ISSUE THREAD

**Issue by JsHuang** [synacktiv/frinet#1]
Hi, can I set the `module `option to a dll and setting `addr` to one of a function in this dll?

I tested in some program with this settings, which result in a huge size of trace file( and need manually stop it to produce more).

**Comment by hexa-synacktiv** [comment]
Hi,
As a disclaimer, we mostly tested the tool on Linux/Android/iOS, only running it on one Windows binary to see if it worked as well there.

I am not 100% sure what the issue is here, so I will restate what I understand :
You are targeting a specific function in a specific lib, the trace never seems to stop and you have to CTRL+C or abort it in some other way.

If this is accurate, then there are three main possible explanations :

1. The function is very "heavy", meaning that it executes a lot of instruction or calls other functions which execute a lot of instruction in a synchronous fashion. In this case there is no simple way of solving the issue, other than tracing a lighter subfunction or setting an end address through '-E end_addr' before the heavy stuff happens. Some other solutions are possible through modifying the tool's code specifically for your scenario, but they are not straightforward.
2. You did not put the start of a function in the addr, which means Frida did not detect where the return statement is, and "onLeave" is never called. To fix this, addr MUST be the first instruction of a function.
3. addr is indeed at the start of a function, but for some reason Frida does not register "onLeave" correctly and it is never called even after the function returns. This can be fixed by manually choosing an end address through '-E end_addr'.

**Comment by JsHuang** [comment]
@hexa-synacktiv Thanks for your explanations, I think the fitst one may be the problem, I test with a small funciton and it works.
